title: Ævum
description: 軌跡
url: https://viriditas.live
baseurl: ""
lang: zh-CN
timezone: Asia/Shanghai
markdown: kramdown
permalink: /posts/:title/
future: false
show_drafts: false
author:
  name: 不是路
  bio: 某人的兔子洞
  avatar: /assets/images/cropped-screenshot-2025-05-29-at-22.13.09.png
announcement: WIP
paginate: 10
paginate_path: "/page/:num/"
license: CC BY-NC-SA 4.0
comments:
  provider: utterances
  repo: ringeringeraja33/Blog
  label: blog-comment
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: feed.xml
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
